version: "3.9"
networks:
  fool-card-game-dev:
    driver: bridge
services:
  app:
    container_name: fool-card-game
    build:
      context: .
      dockerfile: FoolCardGame.Identity/Dockerfile
    ports:
      - "80:80"
    networks:
      - fool-card-game-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fool-card-game
    ports:
      - "5432:5432"
    networks:
      - fool-card-game-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: